version: '3.8'

services:
    app:
        container_name: spotify-obs
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        env_file:
            - .env
        depends_on:
            - mongodb

    mongodb:
        container_name: mongodb
        image: 'mongo'
        ports:
            - '27018:27017'
        volumes:
            - mongodb_data:/data/db

volumes:
    mongodb_data:
